-- 为 users 表添加个人信息字段
ALTER TABLE users 
ADD COLUMN age INT COMMENT '年龄',
ADD COLUMN occupation VARCHAR(100) COMMENT '职业',
ADD COLUMN bio TEXT COMMENT '个人简介',
ADD COLUMN avatar VARCHAR(255) COMMENT '头像URL',
ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

-- 查看更新后的表结构
DESCRIBE users;
